### ISSUE TITLE
发送消息无回复，报错  TypeError: chatgptApi.sendMessage is not a function

### ISSUE THREAD

**Issue by luluyayaa** [dev-zuo/chatgpt-node-vue3#6]

**Comment by luluyayaa** [comment]
C:\Users\lulu\Desktop\chatgpt-node-vue3-main>node server/index.js             
服务开启于 9000 端口
(node:20988) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21)
(node:20988) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise 
rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20988) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
****>>chatgptAPI 

  TypeError: chatgptApi.sendMessage is not a function
      at C:\Users\lulu\Desktop\chatgpt-node-vue3-main\server\index.js:125:14
      at dispatch (C:\Users\lulu\Desktop\chatgpt-node-vue3-main\node_modules\koa-compose\index.js:42:32)
      at C:\Users\lulu\Desktop\chatgpt-node-vue3-main\node_modules\koa-router\lib\router.js:425:16
      at dispatch (C:\Users\lulu\Desktop\chatgpt-node-vue3-main\node_modules\koa-compose\index.js:42:32)
      at C:\Users\lulu\Desktop\chatgpt-node-vue3-main\node_modules\koa-compose\index.js:34:12 
      at dispatch (C:\Users\lulu\Desktop\chatgpt-node-vue3-main\node_modules\koa-router\lib\router.js:430:31)
      at dispatch (C:\Users\lulu\Desktop\chatgpt-node-vue3-main\node_modules\koa-compose\index.js:42:32)
      at session (C:\Users\lulu\Desktop\chatgpt-node-vue3-main\node_modules\koa-session\index.js:41:13)
      at dispatch (C:\Users\lulu\Desktop\chatgpt-node-vue3-main\node_modules\koa-compose\index.js:42:32)
      at bodyParser (C:\Users\lulu\Desktop\chatgpt-node-vue3-main\node_modules\koa-bodyparser\index.js:91:11)

**Comment by dev-zuo** [comment]
1、返回类型不要使用流，切到普通类型试试，看是否能成功。之前发现有可能是额度没了
2、之前没有更新 package.json，刚修改了，您可以尝试拉取最新代码，删除 node_modules，重新 npm install，再运行试试。
另外我的 node 版本是 v16.17.1
